### ISSUE TITLE
Communication channel

### ISSUE THREAD

**Issue by swetankkk** [mozilla/GSOC2020#35]
There aren't any communication channels mentioned here unlike last year's wiki which mentioned the IRC channels of that time.
As of December [Mozilla announced](https://discourse.mozilla.org/t/synchronous-messaging-at-mozilla-the-decision/50620) switch to Riot.
However I coudn't find the new channels
It could be a great help for a lot of potential metees if there is a mention of a communictaion channel!

**Comment by championshuttler** [comment]
@radicalswetank Here you go https://chat.mozilla.org/#/room/#GSOC2020:mozilla.org

**Comment by swetankkk** [comment]
Thanks @championshuttler
