### ISSUE TITLE
spelling mistake of people in mozilla/GSOC2020/README.md

### ISSUE THREAD

**Issue by SATAKSHI08** [mozilla/GSOC2020#50]
![Screenshot (5)_LI](https://user-images.githubusercontent.com/56965113/76956737-9c542000-693a-11ea-8b79-553069d36a60.jpg)

**Comment by dpshekhawat** [comment]
This issue is already solved by me and others also check them out in PR and there are several other grammatical errors which are also optimized.

**Comment by SATAKSHI08** [comment]
all right i will check the pull request.

**Comment by mhoye** [comment]
Sorted, thanks.
