### ISSUE TITLE
idea - media controls

### ISSUE THREAD

**Issue by dpshekhawat** [mozilla/GSOC2020#62]
Here is the idea of adding media controls for sound controlling like play, pause button and various other things like currently playing etc.
This idea came into my mind when I had too many tabs opened in my mozilla browser and youtube was one of them, some music was playing and suddenly due to some reason I wish to pause the music but for that I have to find the youtube tab and then pause it from there, if I had an media control option from where  ever on screen I can control the music.
I have no idea if this already exist or in the browser's addons but if possible I want this feature at same place where the PIP option is available.

**Comment by iprasandeep** [comment]
I think, we have already some extensions for this idea.
