### ISSUE TITLE
Student doubt - Mentors for our own proposals?

### ISSUE THREAD

**Issue by pratiklodha** [mozilla/GSOC2020#7]
Hello, How to get mentors/check mentors' availability for the student's own new project ideas?

**Comment by mhoye** [comment]
It's difficult to simply "find" mentors, unfortunately; it's usually up to the student making the proposal to figure out to whom to make that proposal and convince them of the merits of their idea.  Having said that, discoverability at Mozilla is still difficult, and I'm happy to help, so I'm going to add a note to the README suggesting that people file an issue asking for that sort of help, describing their project in broad strokes, and that I'll try to find the right people to take a look.
