### ISSUE TITLE
voice modules

### ISSUE THREAD

**Issue by kshitij-gavhane** [mozilla/GSOC2020#72]
i was surfing internet. with about 20 tabs open. one of the tab was playing youtube.
i had to control media on Youtube and i was unable to find the tab of Youtube.
what if there is voice command button that will guide me to find the tab.
for example:
if i command "bring youtube to front" it will jump to tab in which youtube is opened.
it will help users to find or access tabs easily and quickly.

**Comment by Rara1410** [comment]
nice idea should need to work

**Comment by imsachinsingh10** [comment]
Hey, will your Organization is going to participate in GSoC'21 ??

**Comment by championshuttler** [comment]
> Hey, will your Organization is going to participate in GSoC'21 ??

No Sorry we are not participating this year

**Comment by imsachinsingh10** [comment]
okay, actually this organization has been part of GSOC for very long i thought that this year also you people will participate, so i thought of contributing to it.

**Comment by kshitij-gavhane** [comment]
@Rara1410 lets work together
